#ex009 - Faça um programa que leia um número inteiro qualquer e mostre na tela a sua tabuada:
n1 = int(input('Digite um número para ver a sua tabuada: '))
print('============')
print('{} x 01 = {}'.format(n1, n1*1))
print('{} x 02 = {}'.format(n1, n1*2))
print('{} x 03 = {}'.format(n1, n1*3))
print('{} x 04 = {}'.format(n1, n1*4))
print('{} x 05 = {}'.format(n1, n1*5))
print('{} x 06 = {}'.format(n1, n1*6))
print('{} x 07 = {}'.format(n1, n1*7))
print('{} x 08 = {}'.format(n1, n1*8))
print('{} x 09 = {}'.format(n1, n1*9))
print('{} x 10 = {}'.format(n1, n1*10))
print('============')
#Acertei 100% desse exercício sem consulta
#Abaixo a resolução do professor neste exercício:
n1 = int(input('Digite um número para ver a sua tabuada: '))
print('=' * 12)
print('{} x {:2} = {}'.format(n1, 1, n1*1))
print('{} x {:2} = {}'.format(n1, 2, n1*2))
print('{} x {:2} = {}'.format(n1, 3, n1*3))
print('{} x {:2} = {}'.format(n1, 4, n1*4))
print('{} x {:2} = {}'.format(n1, 5, n1*5))
print('{} x {:2} = {}'.format(n1, 6, n1*6))
print('{} x {:2} = {}'.format(n1, 7, n1*7))
print('{} x {:2} = {}'.format(n1, 8, n1*8))
print('{} x {:2} = {}'.format(n1, 9, n1*9))
print('{} x {:2} = {}'.format(n1, 10, n1*10))
print('=' * 12)